env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
  tsconfigRootDir: ./
  project:
    - ./tsconfig.json
plugins:
  - react
  - "@typescript-eslint"
rules:
  # react
  react/react-in-jsx-scope: "off"
  react/no-unescaped-entities: "off"
  react/jsx-space-before-closing:
    - warn
    - always

  # vanilla warn
  no-alert: warn
  no-console: warn

  # vanilla error

  # vanilla default
  indent:
    - warn
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always